---
title: "Ensembles de fonctions"
format: html

css: styles.css
---

::: exercise-box
### Exercice 1

Les fonctions suivantes sont-elles en escalier sur $I$ ?

1.  $I = [0; 1]$ et $f(x) = x^2$.

2.  $I = [-1; 1]$ et $f(x) = 0$ pour $x \neq 0$ et $f(0) = 1$.

3.  $I = [1; 5]$ et $f(x) = \lfloor \sqrt{x} \rfloor$.

4.  $I = \left[\frac{1}{5}; 1\right]$ et $f(x) = \lfloor \frac{1}{x} \rfloor$.

5.  $I = [0; 1]$ et $f(x) = \lfloor \frac{1}{x} \rfloor$ si $x \neq 0$ et $f(0) = 0$.

<details>

<summary><strong>Corrigé pour 1</strong></summary>

Par absurde, si $f$ était en escallier, il existerait une subdivision $\sigma = \{x_0=0, x_1, ..., x_n=1\}$ avec $f$ constante sur $]0, x_1[$. Mais $f$ est strictement croissante sur $]0, x_1[$ donc n'est pas constante sur $]0, x_1[$. D'ou $f$ n'est pas en escalier sur $]0, 1[$.

</details>

<details>

<summary><strong>Corrigé pour 2</strong></summary>

Prendre $\sigma = \{-1, 0, 1\}$; en effet,

On a donc $f(x) =0$ $\forall$ $x \in ]-1,0[$ et $f(x) =0$ $\forall$ $x \in ]0,1[$.

D'ou $f$ est en escalier car $\exists$ $\sigma = \{-1, 0, 1\}$.

</details>

<details>

<summary><strong>Corrigé pour 3</strong></summary>

On définit la subdivision $\sigma = \{1, 4, 6\}$. En éffet, $f(x)=1$ si $x \in ]1,4[$ et $f(x)=2$ si $x \in ]4,5[$. Car $x \leq E(x) < x+1$ ce qui implique que $\sqrt{x} \leq \sqrt{E(x)} < \sqrt{x}+1$. Donc, comme il existe une subdivision $\sigma = \{1, 4, 6\}$. Alors, on peut dire que $f$ est en escalier.

</details>

<details>

<summary><strong>Corrigé pour 4</strong></summary>

On définit la subdivision $\sigma = \{\frac{1}{5},\frac{1}{4},\frac{1}{3},\frac{1}{2},1,\}$. En effet, on a si $x \in ]\frac{1}{5},\frac{1}{4}[$ $\Rightarrow$ $\frac{1}{x} \in ]4, 5[$, donc $E[\frac{1}{x}]=4$ . Ainsi de suite.

$$
E[\frac{1}{x}] = \begin{cases}
4 & \text{si } x \in ]4; 5[ \\
3 & \text{si } x \in ]3; 4[ \\
2 & \text{si } x \in ]2; 3[ \\
1 & \text{si } x \in ]1; 2[
\end{cases}
$$

Donc, $$
f(x) = \begin{cases}
\frac{1}{4} & \text{si } x \in \ ]\frac{1}{5}; \frac{1}{4}[ \\
\frac{1}{3} & \text{si } x \in \ ]\frac{1}{4}; \frac{1}{3}[ \\
\frac{1}{2} & \text{si } x \in \ ]\frac{1}{3}; \frac{1}{2}[ \\
1 & \text{si } x \in \ ]\frac{1}{2}; 1[
\end{cases}$$

</details>

<details>

<summary><strong>Corrigé pour 5</strong></summary>

$$ f(x)= \begin{cases}
E[\frac{1}{x}] & \text{si} \ x \neq 0 \\
0 & \text{si} \  x =0
\end{cases}$$ On montre que $f$ n'est pas en escalier sur $I$ par absurde. Supposons que $f$ est en escalier, alors il existe une subdivision $\sigma=\{x_0=0, x_1, ..., x_n=1\}$ telque $f$ est constante sur chaque intervalle $]x_i, x_{i+1}[$, $\forall i \in [|0, n-1 |]$.

On sait que $\forall x_1 \in ]0, 1[$. On peut trouver $p \in \mathbb N^*$, $\frac{1}{p} < x_1 \Leftrightarrow p > \frac{1}{x_1}$. Ainsi, $$ 0 < \frac{1}{p+1}< \frac{1}{p}<x_1$$

$f(\frac{1}{p+1})= E[p+1]= p+1$ $\text{et} \quad f(\frac{1}{p})=E[p]=p$

Et donc sur $]0, x_1[$ $f(\frac{1}{p+1}) \neq f(\frac{1}{p})$

donc pas constante.

Alors $f$ n'est pas en escalier sur $[0,1]$.

</details>
:::

::: exercise-box
### Exercice 2

Soit $f : [0, 3] \to \mathbb{R}$ définie par $f(x) = (x-1)(x-2)$. Trouver une fonction en escalier sur $[0, 3]$ qui vérifie $|\Phi(x) - f(x)| \leq \frac{1}{2}$ pour tout $x \in [0, 3]$.

<details>

<summary><strong>Corrigé</strong></summary>

on a : $f(x)= (x-1)(x-2)=x^2-3x +2$ donc $f'(x)=2x-3$ donc $-3 \leq f'(x) \leq 3$

(car $f'(3)=3$ et soit $|f'(x)| \neq 3$).

Donc, pour tout $(x_1,x_2) \in [0,3]^2.$

$$| f(x_1)-f(x_2)| \leq 3 |x_1-x_2|$$

En prenant $\sigma = \{0, \frac{1}{6},\frac{2}{6}, ... , \frac{18}{6} \}$ et $\phi (x) = f(\frac{K}{6})$, $\forall x \in [\frac{k}{6},\frac{k+1}{6}]$ et $|f(x)-\phi(x)| \leq \frac{1}{2}$ , $\forall x \in [0,3]$.

D'ou,

$$ \phi (x) = f(\frac{K}{6}),\  \forall x \in [\frac{k}{6},\frac{k+1}{6}] $$

</details>
:::

::: exercise-box
### Exercice 3

Soit $a < b$. Démontrer que si $f$ est en escalier sur $[a; b]$ et ne s'annule pas, alors $\frac{1}{f}$ est en escalier sur $[a; b]$.

<details>

<summary><strong>Corrigé</strong></summary>

Soit $a<b$, $f$ est en escalier donc il existe une subdivision $\sigma = \{x_0=a, x_1, ..., x_n=b\}$ et $f$ est constante sur chaque intervalle $]x_i, x_i+1[$ , $\forall i \in [|0, n-1|]$ et $f$ est constante donc supposons que $f(x)=\lambda_i$.

Comme $\lambda_i \neq 0$, $\frac{1}{f(x)} = \frac{1}{\lambda_i}$, $\forall x \in ]x_i, x_i+1[$.

Donc, $\frac{1}{f}$ est en escalier sur $[a,b].$

</details>
:::

::: exercise-box
### Exercice 4

Tout nombre $x \in [0, 1[$ admet une écriture décimale propre unique $0, a_1a_2a_3\ldots$. On note $u_x$ la première décimale $(a_1)$ après la virgule dans l'écriture de $x$. Soit $\Phi : [0, 1] \to \mathbb{R}$ définie par $\Phi(x) = u_x$ pour $x \in [0, 1[$ et $\Phi(1) = 0$. Montrer que $\Phi$ est une fonction en escalier.

<details>

<summary><strong>Corrigé</strong></summary>

Soit \$(\sigma*i) =(\*\frac{i}{10}){i \in [0,10]} \$ une subdivision de $[0, 1]$. Ainsi, $\forall x \in [\frac{i}{10}, \frac{i+1}{10}[$ avec \$i \in [0, 9], on a :

$$ 0,i \leq x < 0,(i+1)$$

Alors, $$ \phi(0,i) \leq \phi(x) < \phi(0,(i+1)) \quad \Rightarrow i \leq \phi(x) < i+1 $$

Donc, $\phi(x)=i$ qui est une constante car $i \in [0,9]$. Puisque $\phi$ est constante sur chacun des intervalles $]\frac{i}{10}, \frac{i+1}{10}[$, $\forall i \in [0,9]$, alors $\phi$ est en escalier su r $[0,1]$.

</details>
:::

::: exercise-box
### Exercice 5

La composée de deux fonctions continues par morceaux est-elle forcément continue par morceaux ?

<details>

<summary><strong>Corrigé</strong></summary>

Considerons les fontions $f: [0,1] \to \mathbb R$ et $g:]0, +\infty[ \to \mathbb R$ données par

$$ f(x)= \begin{cases}
x & \text{si} \quad x \in \ ]0,1] \\
1 & \text{si}\quad x = \ 0 \\
\end{cases}$$

et $$g(x)= \frac{1}{x}$$

La fonction $f$ est continue par morceaux sur $[0,1]$, la fontion $g$ est est continue par morceaux sur $]0, +\infty[$ . La composée $g \circ f$ est correctement définie sur $[0,1]$ mais n'est pas continue par morceaux sur $[0,1]$ (car non bornée). Donc non !

</details>
:::

::: exercise-box
### Exercice 6

On considère la fonction $f$ définie sur $[-1; 1]$ par :

$$
f(x) = \begin{cases}
-2x - 1 & \text{si } x \in ]-1; 0[ \\
x^2 & \text{si } x \in ]0; 1[ \\
0 & \text{si } x \in \{-1; 1\} \\
1 & \text{si } x = 0
\end{cases}
$$

Déterminer une fonction continue $g$ et une fonction en escalier $\phi$ sur $[-1; 1]$ telles que $f = g + \phi$.

<details>

<summary><strong>Corrigé</strong></summary>

$f = g + \phi \quad \Leftrightarrow \quad f-g = \phi \ \in \mathcal{ E}(\mathbb R, \mathbb R)$.

Sur \$ -1 \leq x \< 0\$ , \quad $f(x)-g(x) = c$ , donc \$g(x) = -2x-1-c \$

Sur $0 < x \leq 1$ , \quad  \$f(x)-g(x) = d \$, donc $g(x)= x^2 -d$.

Limite en $0$ : $\lim_{x \to 0^{-}} \, g(x) = -1- c$ et $\lim_{x \to 0^{+}} , g(x) = d$. Donc, $d = 1 + c$ puisque la fonction $g$ est continue, ainsi $c = -\frac{1}{2}$ et $d = \frac{1}{2}$,

$$ \phi(x) = \begin{cases}
c & \text{si} \quad x \ \in \ ]-1, 0[ \\
d & \text{si} \quad x \ \in  \  ]0, 1] \\
\end{cases}$$

$$ g(x) = \begin{cases}
-2x -\frac{1}{2} & \text{si} \quad x \ \in \ [-1, 0] \\
x^2 -\frac{1}{2}  & \text{si} \quad x \ \in  \  [0, 1] \\
\end{cases}$$

</details>
:::

::: exercise-box
### Exercice 7

Soit $f : [0, 1] \to \mathbb{R}$ définie par $f(x) = x$. Soit $n \in \mathbb{N}^*$. Trouver deux fonctions en escalier $\Phi$ et $\Psi$ sur $[0, 1]$ telles que $\Phi \leq f \leq \Psi$ et $f(x) - \Phi(x) \leq \frac{1}{n}$ et $\Psi(x) - f(x) \leq \frac{1}{n}$ pour tout $x \in [0, 1]$.

<details>

<summary><strong>Corrigé</strong></summary>

</details>
:::

::: exercise-box
### Exercice 8

1.  Montrer que les fonctions réglées sur un segment sont forcément bornées.

<details>

<summary><strong>Corrigé</strong></summary>

Supposons que $f$ est réglée alors pour tout $\epsilon > 0$, il existe $\phi \in \mathcal{E} \ ([a,b])$, pour tout $x$ dans $[a,b]$ , $| f(x)-\phi(x)| < 1.$

Comme $\phi$ est bornée, alors $f$ l'est aussi.

</details>
:::

::: exercise-box
### Exercice 9

Soit $f : [0, 1] \to \mathbb{R}$ définie par $f(0) = 1$ et $f(x) = x\lfloor \frac{1}{x} \rfloor$ pour tout $x \in ]0, 1]$.

1.  Donner la formule de $f$ sur chaque intervalle $] \frac{1}{n+1} , \frac{1}{n}]$, $n \in \mathbb{N}^*$. Quelle est l'image de cet intervalle par $f$ ?
2.  Soit $\epsilon > 0$. Trouver $N$ tel que $|1 - f| < \epsilon$ sur $[0, \frac{1}{N}]$.
3.  Avec les notations de (2), montrer qu'il existe une fonction $\Phi$ en escalier sur $[\frac{1}{N}, 1]$ telle que $|\Phi - f| < \epsilon$ sur cet intervalle.
4.  En déduire que $f$ est réglée.

<details>

<summary><strong>Corrigé</strong></summary>

</details>
:::

::: exercise-box
### Exercice 10

Montrer que $f : [0, 1] \to \mathbb{R}$ définie par $f(x) = \frac{1}{x} - \lfloor \frac{1}{x} \rfloor$ si $x \neq 0$ et $f(0) = 1$ n'est pas réglée.

<details>

<summary><strong>Corrigé</strong></summary>

</details>
:::
